language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: cp .travis.oasis _oasis && bash -ex .travis-opam.sh && bash -ex .travis.sh
sudo: true
env:
  global:
    - PACKAGE=thin_lvhd_tools
    - OCAML_VERSION=4.02
    - TESTS=true
    - EXTRA_REMOTES="git://github.com/xapi-project/opam-repo-dev"
    - PINS="conduit:git://github.com/mirage/ocaml-conduit"
